In [ ]:
Student Performance Analyzer

In [ ]:
student = pd.read_csv("/content/student_marks (1).csv")
student.head()

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
0,John,M,05-04-1988,55,45,56,87,21,52,89,65
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53

In [ ]:
student['Maths'].mean()

np.float64(59.6)

In [ ]:
top_performers = student.sort_values(by = ['Maths','Chemistry','English','Physics','Biology','Economics','History','Civics'],ascending = False)
top_performers.head(10)

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
9,Mukesh,M,02-09-1989,96,46,77,83,58,83,46,77
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53
8,Farha,F,12-08-1990,55,63,89,75,78,75,63,89
6,pooja,F,04-05-1987,55,64,61,58,75,58,64,61
0,John,M,05-04-1988,55,45,56,87,21,52,89,65
7,Ritesh,M,25-05-1989,54,76,87,56,25,56,76,87
5,Annu,F,05-04-1988,45,87,52,89,55,89,87,52
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74

In [ ]:
subject_wise_highest_scores = student[['Maths','Physics','Chemistry','English','Biology','Economics','History','Civics']].max()
subject_wise_highest_scores

Maths        96
Physics      96
Chemistry    89
English      89
Biology      96
Economics    89
History      89
Civics       89
dtype: int64

In [ ]:
subject_columns = ['Maths','Physics','Chemistry','English','Biology','Economics','History','Civics']
student['Average_Score'] = student[subject_columns].mean(axis=1)
def assign_grade(score):
    if score >= 80:
        return 'A'
    elif score >= 60:
        return 'B'
    elif score >= 40:
        return 'C'
    else:
        return 'D'
student['Grade'] = student['Average_Score'].apply(assign_grade)
student[['Unnamed: 0', 'Average_Score', 'Grade']].head()

In [ ]:
student.describe()

,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.0000
mean,59.600000,72.300000,75.300000,69.700000,64.700000,72.700000,69.700000,60.5000
std,19.460501,20.661559,14.000397,14.453373,26.998148,14.629119,14.453373,25.3432
min,25.000000,45.000000,52.000000,46.000000,21.000000,52.000000,46.000000,2.0000
25%,54.250000,56.250000,65.000000,59.250000,54.250000,58.750000,59.250000,52.2500
50%,55.000000,70.000000,78.000000,69.500000,66.500000,76.000000,69.500000,63.0000
75%,70.750000,93.750000,86.750000,81.250000,87.000000,86.000000,81.250000,76.2500
max,96.000000,96.000000,89.000000,89.000000,96.000000,89.000000,89.000000,89.0000